logging:
  level:
    .: error
    org.springframework: ERROR
    com.mkyong: ERROR

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

server:
  port: 49200


cronExpression: "* 0/5 8-19 ? * MON-FRI"    #Delay in seconds to check JIRA
proxy:                                      #Not mandatory, just in case of need
proxy-port:                                 #Not mandatory, just in case of need
java-home:                                  #Not mandatory, just in case of need

#Set your own password to encrypt property values
#Get encrypted property values using this command:
#java -cp jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input="non_encrypted_property_value" password=mySecretKey algorithm=PBEWithMD5AndDES
jasypt:
  encryptor:
    password: mySecretKey

# JIRA global configuration
jira:
  username: ToFill                      #JIRA username
  password: ToFill                      #JIRA password
  url: ToFill                           #JIRA url
  filter-id: ToFill                     #JIRA filter id that has been exporter to XML data in JIRA
  element-tag-name: item                #JIRA XML tag name for the element that represents the JIRA issues
  key-element-tag-name: key             #JIRA XML tag name for the element that represents the ID of the JIRA issue
  priority-name: priority               #JIRA XML tag name for the element that represents the priority of the JIRA issues
  priority:                             #Types of priority in JIRA
     - "P1"
     - "P2"
     - "P3"

# Slack global configuration
slack:
  active: true
  colors:
    - "FD2F03"
    - "FD9703"
    - "0356FD"
  fields:
    slack-message:                                #Map between fields of the Slack message and the Jira issue
      title: "ToFill"
      title-link: "ToFill"
  subfields:                                      #Map between subfields of the Slack message and the Jira issue
      1:
        title: "ToFill"
        value: "ToFill"
        short: true
      2:
        title: "ToFill"
        value: "ToFill"
        short: true

# List of JIRA filters to check
filtersConf:
  filters:
    first:
      filter-id: ToFill                      #JIRA filter id that has been exporter to XML data in JIRA
      slack-token: ToFill                    #Slack token for the bot authentication
      local-file-stored-issues: ToFill       #Local file that contains the issues already treated
      slack-active: false
      slack-channels:                        #Slack channels to be use
        - "channel P1"
        - "channel P2"
        - "channel P3"
    second:
      filter-id: ToFill                      #JIRA filter id that has been exporter to XML data in JIRA
      token: ToFill                          #Slack token for the bot authentication
      local-file-stored-issues: ToFill       #Local file that contains the issues already treated
      slack-active: true
      slack-channels:                        #Slack channels to be use
        - "channel P1"
        - "channel P2"
        - "channel P3"