logging:
  level:
    .: error
    org.springframework: ERROR
    com.mkyong: ERROR

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

server:
  port: 49200

jira:
  java-home:                            #In case of need
  startTime: "08:00"                    #Check begins at this time
  endTime: "19:00"                      #Check ends at this time
  minutes: 15                           #Check every X minutes
  username: ToFill                      #JIRA username
  password: ToFill                      #JIRA password
  url: ToFill                           #JIRA url
  filter-id: ToFill                     #JIRA filter id that has been exporter to XML data in JIRA
  element-tag-name: item                #JIRA XML tag name for the element that represents the JIRA issues
  key-element-tag-name: key             #JIRA XML tag name for the element that represents the ID of the JIRA issue
  local-file-stored-issues: issues.txt  #Local file that contains the issues already treated
  priority-name: priority               #JIRA XML tag name for the element that represents the priority of the JIRA issues
  priority:                             #Types of priority in JIRA
     - "P1"
     - "P2"
     - "P3"


slack:
  active: false
  token: ToFill                                          #Slack token for the bot authentication
  channels:                                              #Slack channels to be use
    - "channel P1"
    - "channel P2"
    - "channel P3"
  colors:
    - "FD2F03"
    - "FD9703"
    - "0356FD"
  fields:
    slack-message:                                       #Map between fields of the Slack message and the Jira issue
      title: "ToFill"
      title-link: "ToFill"
      text: "ToFill"
  subfields:                                      #Map between subfields of the Slack message and the Jira issue
      1:
        title: "ToFill"
        value: "ToFill"
        short: true
      2:
        title: "ToFill"
        value: "ToFill"
        short: true
